### ISSUE TITLE
Tests are producing false positives

### ISSUE THREAD

**Issue by matthiaseigner** [rimiti/redis-keyman#31] opened 2018-04-24 10:14 UTC
some tests are even passing when the expects are changed. Following example will pass
```javascript
it('Guest to view blogs', () => {
   acl.allow('guest', 'blogs', 'view', (err) => {
      expect(!err);
      expect(err);
   });
});
```
It seems that expect is used incorrectly in the tests.

Correct code should look like this:
```javascript
it('Guest to view blogs', () => {
   acl.allow('guest', 'blogs', 'view', (err) => {
      expect(err).toBeNull();
  });
});
```

**Comment by rimiti** [comment] 2018-04-24 10:33
Hello @matthiaseigner,

Could you propose a pull request ?

**Comment by matthiaseigner** [comment] 2018-04-24 10:36
Yes, i'm currently working on it.

**Comment by rimiti** [comment] 2018-04-24 12:17
You rock ! 👍 
I'm waiting for it to include it into the next release #33.

**Comment by matthiaseigner** [comment] 2018-04-24 21:47
After changing all expects all the tests succeeded for the stores ```['Memory', 'Redis', 'MongoDB']``` but 3 tests failed for ```'MySQL'```.

The three tests are:

- Can jsmith edit blogs
- Can test@test.com edit blogs
- Can userId=1 edit blogs?

The tests expect the user to have the permission ```edit``` for the resource ```blogs```.
All three users have just one role ```['member']``` which actually has no permissions to edit blogs.
The only permissions in the db for blogs are
```
allows_blogs | {"guest":["view"],"foo":["edit","view"],"bar":["view","delete"],"admin":["*"],"fumanchu":["get"]}
```
Am i missing something or are these tests wrong?

**Comment by rimiti** [comment] 2018-04-25 09:59
In first, thank you for your work it's really nice / useful.
I think the problem is the MySQL store. I'll create a new issue to investigate this point but without checking the code, it's a MySQL store bug for me.

**Comment by rimiti** [comment] 2019-05-04 09:31
Hello @matthiaseigner,

I'm closing this issue, all test are now more strict. There are no more false positives.

**Closed as completed by rimiti** 2019-05-04 09:31 UTC
